#include "Style.hpp"
#include "Globals.hpp"

Style::Style() {
	Update(DEF_WINDOW_WIDTH, DEF_WINDOW_HEIGHT);
}

void Style::Update(int w, int h) {
	DISPLAY_WIDTH						= w;
	DISPLAY_HEIGHT						= h;

	//############################### EDIT BOX ######################################

	WORD_MARGIN_TOP						= 20;
	WORD_MARGIN_LEFT					= 20;
	WORD_WIDTH							= 711;
	WORD_HEIGHT							= 26;

	//################################### WORDS ##########################################

	WORDS_MARGIN_TOP					= WORD_MARGIN_TOP + WORD_HEIGHT + 7;
	WORDS_MARGIN_LEFT					= WORD_MARGIN_LEFT;
	WORDS_MARGIN_BOTTOM					= 315;
	WORDS_WIDTH							= 711;
	WORDS_HEIGHT						= DISPLAY_HEIGHT - WORDS_MARGIN_BOTTOM;

	WIDE_WORDS_MARGIN_BOTTOM			= 85;
	WIDE_WORDS_HEIGHT					= DISPLAY_HEIGHT - WORDS_MARGIN_TOP - WIDE_WORDS_MARGIN_BOTTOM;
	
	TEST_WORDS_HEIGHT					= 60;

	//################################### WORDS BUTTONS ##################################

	WDBTN_MARGIN_TOP					= WORDS_MARGIN_TOP + WORDS_HEIGHT;
	WDBTN_MARGIN_LEFT					= WORDS_MARGIN_LEFT;
	WDBTN_WIDTH							= 84;
	WDBTN_HEIGHT						= 24;

	WSABTN_MARGIN_TOP					= WDBTN_MARGIN_TOP;
	WSABTN_MARGIN_LEFT					= WDBTN_MARGIN_LEFT + WDBTN_WIDTH - 1;
	WSABTN_WIDTH						= 104;
	WSABTN_HEIGHT						= 24;

	WIDE_WDBTN_MARGIN_TOP				= WORDS_MARGIN_TOP + WIDE_WORDS_HEIGHT;
	WIDE_WSABTN_MARGIN_TOP				= WIDE_WDBTN_MARGIN_TOP;

	TEST_WDBTN_MARGIN_TOP				= WORDS_MARGIN_TOP + TEST_WORDS_HEIGHT;
	TEST_WSABTN_MARGIN_TOP				= TEST_WDBTN_MARGIN_TOP;

	//################################### DICS ###########################################

	DICS_MARGIN_TOP						= 20;
	DICS_MARGIN_LEFT					= WORD_MARGIN_LEFT + WORD_WIDTH + 10;
	DICS_MARGIN_BOTTOM					= WORDS_MARGIN_BOTTOM;
	DICS_WIDTH							= 246;
	DICS_HEIGHT							= DISPLAY_HEIGHT - DICS_MARGIN_BOTTOM + WORDS_MARGIN_TOP - DICS_MARGIN_TOP;
	
	WIDE_DICS_MARGIN_BOTTOM				= WIDE_WORDS_MARGIN_BOTTOM;
	WIDE_DICS_HEIGHT					= DISPLAY_HEIGHT - WIDE_DICS_MARGIN_BOTTOM - DICS_MARGIN_TOP;
	
	TEST_DICS_HEIGHT					= TEST_WORDS_HEIGHT + WORDS_MARGIN_TOP - DICS_MARGIN_TOP;

	//################################### DICS BUTTONS ###################################

	DNBTN_MARGIN_TOP					= DICS_MARGIN_TOP + DICS_HEIGHT;
	DNBTN_MARGIN_LEFT					= DICS_MARGIN_LEFT;
	DNBTN_WIDTH							= 60;
	DNBTN_HEIGHT						= 24;

	DDBTN_MARGIN_TOP					= DNBTN_MARGIN_TOP;
	DDBTN_MARGIN_LEFT					= DNBTN_MARGIN_LEFT + DNBTN_WIDTH - 1;
	DDBTN_WIDTH							= 84;
	DDBTN_HEIGHT						= 24;

	DSABTN_MARGIN_TOP					= DNBTN_MARGIN_TOP;
	DSABTN_MARGIN_LEFT					= DDBTN_MARGIN_LEFT + DDBTN_WIDTH - 1;
	DSABTN_WIDTH						= 104;
	DSABTN_HEIGHT						= 24;

	WIDE_DNBTN_MARGIN_TOP				= DICS_MARGIN_TOP + WIDE_DICS_HEIGHT;
	WIDE_DDBTN_MARGIN_TOP				= WIDE_DNBTN_MARGIN_TOP;
	WIDE_DSABTN_MARGIN_TOP				= WIDE_DNBTN_MARGIN_TOP;

	TEST_DNBTN_MARGIN_TOP				= DICS_MARGIN_TOP + TEST_DICS_HEIGHT;
	TEST_DDBTN_MARGIN_TOP				= TEST_DNBTN_MARGIN_TOP;
	TEST_DSABTN_MARGIN_TOP				= TEST_DNBTN_MARGIN_TOP;

	//################################### TEST ###########################################

	TEST_MARGIN_TOP						= WDBTN_MARGIN_TOP + WDBTN_HEIGHT + 13;
	TEST_MARGIN_LEFT					= WORD_MARGIN_LEFT;
	TEST_WIDTH							= 967;
	TEST_HEIGHT							= 136;

	WIDE_TEST_MARGIN_TOP				= WORD_MARGIN_TOP;
	WIDE_TEST_MARGIN_LEFT				= DICS_MARGIN_LEFT + DICS_WIDTH + 10;
	WIDE_TEST_WIDTH						= DISPLAY_WIDTH - WIDE_TEST_MARGIN_LEFT - 34;
	WIDE_TEST_HEIGHT					= (word) (0.5 * DISPLAY_HEIGHT);
	
	TEST_TEST_MARGIN_TOP				= TEST_WDBTN_MARGIN_TOP + WDBTN_HEIGHT + 13;
	TEST_TEST_MARGIN_BOTTOM				= 89;
	TEST_TEST_HEIGHT					= DISPLAY_HEIGHT - TEST_TEST_MARGIN_TOP - TEST_TEST_MARGIN_BOTTOM;

	//################################### ANSWER #########################################

	ANSWER_MARGIN_TOP					= TEST_MARGIN_TOP + TEST_HEIGHT + 1;
	ANSWER_MARGIN_LEFT					= WORD_MARGIN_LEFT;
	ANSWER_WIDTH						= 881;
	ANSWER_HEIGHT						= 26;

	WIDE_ANSWER_MARGIN_TOP				= WIDE_TEST_MARGIN_TOP + WIDE_TEST_HEIGHT + 1;
	WIDE_ANSWER_MARGIN_LEFT				= WIDE_TEST_MARGIN_LEFT;
	WIDE_ANSWER_WIDTH					= DISPLAY_WIDTH - WIDE_TEST_MARGIN_LEFT - 120;
	WIDE_ANSWER_HEIGHT					= 26;
	
	TEST_ANSWER_MARGIN_TOP				= TEST_TEST_MARGIN_TOP + TEST_TEST_HEIGHT + 1;

	//################################### TEST BUTTONS ###################################

	TSBTN_MARGIN_TOP					= TEST_MARGIN_TOP + TEST_HEIGHT;
	TSBTN_MARGIN_LEFT					= ANSWER_MARGIN_LEFT + ANSWER_WIDTH + 1;
	TSBTN_WIDTH							= 29;
	TSBTN_HEIGHT						= 28;

	TEBTN_MARGIN_TOP					= TSBTN_MARGIN_TOP;
	TEBTN_MARGIN_LEFT					= TSBTN_MARGIN_LEFT + TSBTN_WIDTH - 1;
	TEBTN_WIDTH							= 29;
	TEBTN_HEIGHT						= 28;

	TCBTN_MARGIN_TOP					= TSBTN_MARGIN_TOP;
	TCBTN_MARGIN_LEFT					= TEBTN_MARGIN_LEFT + TEBTN_WIDTH - 1;
	TCBTN_WIDTH							= 29;
	TCBTN_HEIGHT						= 28;

	WIDE_TSBTN_MARGIN_TOP				= WIDE_TEST_MARGIN_TOP + WIDE_TEST_HEIGHT;
	WIDE_TSBTN_MARGIN_LEFT				= WIDE_ANSWER_MARGIN_LEFT + WIDE_ANSWER_WIDTH + 1;

	WIDE_TEBTN_MARGIN_TOP				= WIDE_TSBTN_MARGIN_TOP;
	WIDE_TEBTN_MARGIN_LEFT				= WIDE_TSBTN_MARGIN_LEFT + TSBTN_WIDTH - 1;

	WIDE_TCBTN_MARGIN_TOP				= WIDE_TSBTN_MARGIN_TOP;
	WIDE_TCBTN_MARGIN_LEFT				= WIDE_TEBTN_MARGIN_LEFT + TEBTN_WIDTH - 1;

	TEST_TSBTN_MARGIN_TOP				= TEST_TEST_MARGIN_TOP + TEST_TEST_HEIGHT;
	TEST_TEBTN_MARGIN_TOP				= TEST_TSBTN_MARGIN_TOP;
	TEST_TCBTN_MARGIN_TOP				= TEST_TSBTN_MARGIN_TOP;

	//################################### LABELS #########################################

	WORDS_LABEL_SPACE					= 85;
	WORDS_LABEL_MARGIN_TOP				= WORDS_MARGIN_TOP + WORDS_HEIGHT + 3;
	WORDS_LABEL_MARGIN_LEFT				= WSABTN_MARGIN_LEFT + WSABTN_WIDTH + 10;
	WIDE_WORDS_LABEL_MARGIN_TOP			= WORDS_MARGIN_TOP + WIDE_WORDS_HEIGHT + 3;
	TEST_WORDS_LABEL_MARGIN_TOP			= WORDS_MARGIN_TOP + TEST_WORDS_HEIGHT + 3;
}